---

- name: Deploy the rabbitmq-notification-cleanup for purging notification queues
  hosts: rabbitmq_all[0]
  tasks:
  - name: Drop the rabbitmq-notification-cleanup script into place
    copy:
      src: files/rabbitmq-notification-cleanup.sh
      dest: /root
      mode: 0755
  - name: Add the script execution to cron
    cron:
      minute: "*
      hour: "*/2"
      day: "*"
      month: "*"
      weekday: "*"
      job: "bash /root/rabbitmq-notification-cleanup.sh"
